name: facvae
channels:
  - pytorch
  - nvidia
dependencies:
  - pytorch
  - pytorch-cuda=11.8
  - python=3.9
  - pip
  - pip:
    - --extra-index-url https://pypi.nvidia.com
    - git+https://github.com/alisiahkoohi/scattering_covariance
    - git+https://github.com/alisiahkoohi/insight_src_sep
    - matplotlib
    - tensorboard
    - obspy
    - mpire
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - gitpython
    - termcolor
    - h5py
    - seaborn
    - cuml-cu11==23.12.*
    - cudf-cu11==23.12.*
