name: facvae
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - nvidia::cudatoolkit=11.6
  - python==3.9
  - pytorch::pytorch
  - pip
  - pip:
    - git+https://github.com/alisiahkoohi/scattering_covariance
    - matplotlib
    - tensorboard
    - obspy
    - mpire
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - gitpython
    - termcolor
    - h5py
    - seaborn
    - umap-learn
    - cudf-cu11==23.12.*
    - cuml-cu11==23.12.*
    - protobuf==3.20.3
  - extra:
    - --extra-index-url=https://pypi.nvidia.com