name: fac-vae
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - nvidia::cudatoolkit=11.6
  - python==3.9
  - pytorch::pytorch
  - pytorch::torchvision
  - pip
  - pip:
    - git+https://github.com/alisiahkoohi/scatcov
    - matplotlib
    - tensorboard
    - obspy
    - mpire
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - gitpython
    - termcolor
