name: fac-vae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pytorch
  - torchvision
  - pip
  - cpuonly
  - pip:
    - git+https://github.com/alisiahkoohi/scattering_covariance
    - matplotlib
    - tensorboard
    - obspy
    - mpire
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - tqdm
    - gitpython
    - termcolor
